version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: gokul

#  frontend:
#    build:
#      context: ./app/javascript
#      dockerfile: ./Dockerfile
#    volumes:
#      - .:/app
#    ports:
#      - 3000:3000
#    image: react_learning
#    container_name: react_learning_container
#    command: bash -c "npm start"

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 4000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
      - ../bundler_gems:/usr/local/bundle/
    links:
      - db
    ports:
      - 4000:4000
    depends_on:
      - db