#version: "3.9"
#services:
#  web:
#    build: .
#    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
#    volumes:
#      - .:/myapp
#      - ../bundler_gems:/usr/local/bundle/
#    ports:
#      - "3000:3000"

version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: gokul

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
      - ../bundler_gems:/usr/local/bundle/
    links:
      - db
    ports:
      - "3000:3000"
    depends_on:
      - db