version: "3.9"
services:
  frontend:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - 3000:3000
    image: react_learning
    container_name: react_learning_container
    command: npm start
